Feature/san akel/aoil v2.0 dev
GEOS-ESM/GMAO_Shared pull request #126
Opened 2020-10-02 01:18 UTC by sanAkel

Updates in module `atmOcnIntlayer` :

resolve https://github.com/GEOS-ESM/GEOSgcm_GridComp/issues/356

2020-10-02 01:26 UTC, sanAkel commented
@tclune, I recall you said something about the change log. But I don't know what to add ... even in a `PR`?

If yourself or @mathomp4 give some clues, I will fill in what is needed. 
Thank you!

2020-10-02 12:25 UTC, tclune commented on GEOS_Shared/atmOceanIntLayer.F90
> +private SIMPLE_SW_ABS,      &
A default PRIVATE clause is preferred to an explicit list.     Otherwise if someone inadvertently declares a module variable further down it will default to PUBLIC.      I don't immediately recall if you can "confirm" the default PRIVATE with explicit, but I think you can.     Otherwise you can always mention the explicit list of private things in a comment.

2020-10-02 12:29 UTC, tclune requested changes
Since there is only the one small change requested,  and GitHub showed your branch was initially out-of-date, it is probably best to make the edit directly on GitHub.

2020-10-02 12:37 UTC, tclune commented
I have added e template ChangeLog.md to the PR so satisfy our new requirement.     Would not hurt if @sanAkel could edit to add content.

2020-10-02 13:48 UTC, mathomp4 commented
@sanAkel I think @tclune and I figured this out. You hadn't updated/merged in the latest `main` into your branch, and thus it didn't have the `CHANGELOG.md` that was added after you branched off.

But, the branch was updated by GitHub (clicked a button) and your branch should now have a `CHANGELOG.md` file. That is what requires an edit.

2020-10-02 16:27 UTC, sanAkel commented on GEOS_Shared/atmOceanIntLayer.F90
> +private SIMPLE_SW_ABS,      &
@tclune thank you! This is done.

2020-10-02 16:29 UTC, sanAkel commented
> @sanAkel I think @tclune and I figured this out. You hadn't updated/merged in the latest `main` into your branch, and thus it didn't have the `CHANGELOG.md` that was added after you branched off.
> 
> But, the branch was updated by GitHub (clicked a button) and your branch should now have a `CHANGELOG.md` file. That is what requires an edit.

Updated `CHANGELOG.md` Thanks!

2020-10-02 17:12 UTC, tclune approved these changes
Looks good.  Thanks.

2020-10-13 17:06 UTC, sdrabenh approved these changes

2020-10-13 17:06 UTC, merged