add depedency to turn on BUILD_SHARED_LIBS
GEOS-ESM/GMAO_Shared pull request #136
Opened 2020-11-12 21:38 UTC by weiyuan-jiang

2020-11-13 12:57 UTC, tclune requested changes
As per the other ticket - why is there a new dependency?

Also, please delete lines rather than commenting them.  (Lines 146 and 249)

2020-11-13 21:27 UTC, weiyuan-jiang commented
Again, this is not new dependency. We got away with it because we never use some subroutines

2020-11-14 00:31 UTC, tclune submitted a review, later dismissed

2020-11-18 20:48 UTC, sdrabenh submitted a review, later dismissed

2020-11-18 20:51 UTC, mathomp4 commented
I am putting a blocker tag on this until I can consult with @weiyuan-jiang about the GNU/bufrlib issue.

2020-11-25 14:23 UTC, mathomp4 approved these changes

2020-11-25 17:50 UTC, merged