Feature/rtodling/v10 17 3 br
GEOS-ESM/GMAO_Shared pull request #166
Opened 2021-03-24 14:47 UTC by rtodling

Guys,

This is a fold (rather than a merge in the proper sense of the word) for GMAO_Shared where I (think I) have the stuff that is in 5.27 combined w/ what is in the develop/main branch of GMAO_Shared as used by the model group.

I tried bringing this version back into 5.27 to give it a try, but aside from triviality in the CMakeLists related to MAPL vs MAPL_base, I am finding that the changes in @GMAO_Shared/GEOS_Share   are a lot more involved bring back into the DAS - it will require editing back the MAPLmod - MAPL changes in the source code ... not sure that's worth for me to make sure the changes I made a still consistent and work within the DAS. I might still try doing that, but I should not hold you back in trying to bring this in sync w/ your placing merge of DAS and MAPL 2+other.

Let me know what you think.
Ricardo

2021-03-24 14:51 UTC, tclune submitted a review, later dismissed
cmake changes ok.

2021-03-24 15:07 UTC, mathomp4 requested changes
Huh. I think I clicked the wrong button...

2021-03-24 15:07 UTC, mathomp4 commented on GMAO_gfio/CMakeLists.txt
> +endif ()
@rtodling Can you restore the `if (F2PY_FOUND)` code block from `main` and remove the `include(UseF2Py)`? I added the `F2PY_FOUND` blocks in GEOS so that systems where f2py doesn't exist or doesn't work correctly (which is pretty much every single system that isn't NASA/NAS/NCCS) this gives a way to avoid building the f2py code.

2021-03-24 15:25 UTC, tclune commented
One thing that we may want to contemplate to simplify updating ADAS to the latest versions of the infrastructure is to split GMAO_Shared into its separate repos for each directory.    At least then, ADAS could probably get to the latest of almost everything and we could focus on just the pieces that are problematic.

Of course it would have been more useful to do this a year ago.   But still worth considering.

2021-03-25 14:41 UTC, rtodling commented
I think splitting might be okay - but I'd suggest getting this to work as they are for the moment.

2021-03-25 14:45 UTC, rtodling commented on GMAO_gfio/CMakeLists.txt
> +endif ()
I am not sure I touch the CMakefile in this respect ... but I confess I don't remember. The answer is yes, you can restore if you want.

2021-03-25 15:23 UTC, mathomp4 commented on GMAO_gfio/CMakeLists.txt
> +endif ()
I converted it back. And apparently my CMake indentation has changed since I wrote it. That's why there are two commits 😄

2021-04-01 13:33 UTC, rtodling commented
Any update on this? Do you need me to fix the small glitches?

2021-04-01 13:43 UTC, mathomp4 commented
> Any update on this? Do you need me to fix the small glitches?

Whoops. This got lost on my radar. Let me try and fix the build issue.

2021-04-01 17:00 UTC, mathomp4 commented
@sdrabenh As far as I can see, this is a zero-diff update to GMAO_Shared in so far as the GEOSgcm cares. I did C48 and all was zero-diff.

2021-04-01 20:07 UTC, sdrabenh commented
This PR looks okay to me and passes all my tests. Before I approve and merge, I want to ping @biljanaorescanin and @yvikhlya to make sure this doesn't inadvertently create issues with ldas or the coupled model, respectively.

2021-04-01 20:56 UTC, yvikhlya commented
> This PR looks okay to me and passes all my tests. Before I approve and merge, I want to ping @biljanaorescanin and @yvikhlya to make sure this doesn't inadvertently create issues with ldas or the coupled model, respectively.

None of these updates affects the coupled model as I see it.

2021-04-02 02:25 UTC, biljanaorescanin commented
> This PR looks okay to me and passes all my tests. Before I approve and merge, I want to ping @biljanaorescanin and @yvikhlya to make sure this doesn't inadvertently create issues with ldas or the coupled model, respectively.

I think we are good as well.

2021-04-02 13:02 UTC, sdrabenh approved these changes

2021-04-02 13:07 UTC, mathomp4 approved these changes

2021-04-02 13:08 UTC, mathomp4 commented
Wow. I approved this PR for a lot of teams. 😄

2021-04-02 13:10 UTC, merged